services:
  backend:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    environment:
      DATABASE_URL: postgres://academy:academy@host.docker.internal:5432/electricity
      PORT: 3000
    ports:
      - '3000:3000'
