services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    environment:
      DATABASE_URL: postgres://academy:academy@host.docker.internal:5432/electricity
      PORT: 3000
    ports:
      - '3000:3000'
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        BUILD_CONFIG: development
    ports:
      - '4200:80'
    depends_on:
      - backend
